site_name: My Docs
site_url: https://beispielmeispiel.example
theme:
  name: material
  font:
    text: Mallanna
    code: Red Hat Display
  logo: assets/bug.webp
  features: 
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: white
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/account-cowboy-hat-outline
        name: Light mode
      primary: black
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  - admonition
  - pymdownx.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: simple/pythonanywhere
      link: https://www.nuernberg.de/internet/rudolf_diesel_fachschule/

copyright: Copyright &copy; 2025 WIV2